### ISSUE TITLE
Class 'Normalizer' not found

### ISSUE THREAD

**Issue by garak** [DavidePastore/codice-fiscale#40]
Tried to install this and running tests with php 7.2, got:

>Error: Class 'Normalizer' not found

I guess that some requirement is missing in composer.json
Moreover, I think that declaring php supported versions could be useful

**Comment by DavidePastore** [comment]
Hi @garak. Thanks for reporting this issue. According to the `composer.json` file, the class Normalizer is included in the `intl` extension. You can find the given declaration [here](https://github.com/DavidePastore/codice-fiscale/blob/master/composer.json#L17). Since it was released in the 0.5.1 version, could you please check if you're using it or a newer one. Anyway, if you think this won't work, we could change it.
You're right when you say that a range of supported PHP versions should be defined in the `composer.json` file.

**Comment by garak** [comment]
Question is that you're using an extension without requiring it.
I easily solved by installing intl, but this is not what I expect (to be clear: I expect that if I'm able to install a library, I should also be able to run it)

**Comment by DavidePastore** [comment]
The `intl` extension is [already required](https://github.com/DavidePastore/codice-fiscale/blob/master/composer.json#L17) in the `composer.json` file. If you are able to run `composer install`, then I was expecting Composer to tell you that you're missing it.
What version of the package are you using?

**Comment by garak** [comment]
Unfortunately, since you committed composer.lock, that requirement is completely ignored.
